apiVersion: apps/v1
kind: Deployment
metadata:
  name: sava-product
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: sava-product
        image: vampio/sava-product:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
